### ISSUE TITLE
Ability to verify order?

### ISSUE THREAD

**Issue by drsharp** [kucaahbe/rspec-html-matchers#15]
Hello!

Is there any way to verify order? For example, if I have:

```
<div><span>one</span><span>two</span></div>
```

and test it with:

```
output.should have_tag(:div) do
  with_tag(:span, :text => 'one')
  with_tag(:span, :text => 'two')
end
```

it passes. But if I then change it to:

```
<div><span>two</span><span>one</span></div>
```

it still passes.

I can't see a way to verify that the first span MUST come before the second in the HTML. Any thoughts?

**Comment by randoum** [comment]
I'll close this old issue, as there is no sorting option. Anyone's welcome to open a PR on this.
Thanks
