### ISSUE TITLE
Nested "with_tag"s

### ISSUE THREAD

**Issue by manuelmeurer** [kucaahbe/rspec-html-matchers#24]
As far as I can see, this doesn't work yet:

``` ruby
html.should have_tag(:div, with: { class: 'navbar' }) do
  with_tag :div, with: { class: 'navbar-inner' } do
    with_tag :div, with: { class: 'container' }
  end
end
```

Or rather, it works, but it passes regardless of whether the `container` div is really nested in the `navbar-inner` div, it could be on the same level or even nested the other way around.

Is that something that is supposed to work right now?
Looking at the code, it might just be about setting `@__current_scope_for_nokogiri_matcher` correctly when calling `with_tag`, right?

**Comment by ericgriffis** [comment]
@kucaahbe I know this is old, but I encountered the same issue. Has any progress been made on this issue? I would be happy to help out

**Comment by randoum** [comment]
@ericgriffis if you are still on this, would you mind to check #59 and see if your issues are fixed ?

**Comment by randoum** [comment]
@ericgriffis please have a try with 0.9.0 see if your issue is solved
Otherwise, feel free to reopen with more details
