### ISSUE TITLE
content option missing

### ISSUE THREAD

**Issue by BroiSatse** [kucaahbe/rspec-html-matchers#36]
Hi guys, I was looking everywhere in the code but it seems that content option (mentioned in readme) is just there any more? I've been looking for it as I cannot get my tests to fail, and apparently it has been removed. 

In that case I think there are two possible approaches - could you please either remove it from the readme file or put it back into the code? I am happy to make any of those, your call which option is better.

(+ obviously there is a third option that I just failed to find it ;))

**Comment by kucaahbe** [comment]
@BroiSatse looks like it was either removed or was never added) sorry about that and thanks for raising issue!
