### ISSUE TITLE
Match attribute with any value

### ISSUE THREAD

**Issue by vfonic** [kucaahbe/rspec-html-matchers#40]
Hi,

Thanks for great gem!

I'm writing a test for a helper method for `<img srcset="" />`. I don't want srcset attribute to be rendered when it's not provided in options (when it's empty).

I'm trying to match if the attribute renders at all with any value. Is this possible?

Another use case that comes to my mind would be: `<input type="checkbox" checked />` or any similar form tag.

**Comment by kucaahbe** [comment]
correct @vfonic this is not implemented for now, and honestly not sure if I have time for this in some near future, so would be awesome if we could have pull request for that ;)

**Comment by vfonic** [comment]
Thanks for reply @kucaahbe 
I'm also short on time lately, but if I find any, I'll send a PR.

**Comment by kucaahbe** [comment]
Thanks @vfonic !

**Comment by skalee** [comment]
@vfonic Why not `with_tag("img[srcset]")`?

**Comment by getaaron** [comment]
@skalee FYI, I just updated the README to show this approach

**Comment by vfonic** [comment]
Great, thanks!
