### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [kucaahbe/rspec-html-matchers#45]
Would it be possible to add a LICENSE file to clarify what license applies to this software?
thanks

**Comment by grantneufeld** [comment]
This project’s [readme lists the MIT license](https://github.com/kucaahbe/rspec-html-matchers/blob/master/README.md#mit-licensed).
So, that could presumably just be copied into a LICENSE.md file (like the main [rspec project LICENSE file](https://github.com/rspec/rspec/blob/master/LICENSE.md)).

**Comment by kucaahbe** [comment]
👍 for moving license info into separate file, as how this is done in most open source projects. I'm sorry, right now have no time for this, so pull request will be appreciated and new version released.

**Comment by kucaahbe** [comment]
please, checkout 0.7.3 version

**Comment by andrewdavidmackenzie** [comment]
Thanks!
