### ISSUE TITLE
Can't test for html or body tags

### ISSUE THREAD

**Issue by getaaron** [kucaahbe/rspec-html-matchers#48]
This test passes, but it should fail:

``` ruby
describe "index" do
  it "does something weird" do
    expect("<h1>just a header</h1>").to have_tag("html")
  end
end
```

The same behavior exists with `have_tag("body")`.

I think it's because of [this line](https://github.com/kucaahbe/rspec-html-matchers/blob/8aa8bb06d345f283a6b81eaea2857d9d2210ec2b/lib/rspec-html-matchers.rb#L108), which passes the string straight into `Nokogiri::HTML`.

Two questions:
1. Is there a workaround where I can test for `html` and `body` tags?
2. If not, should `have_tag` raise an exception when it's passed these tags so developers know not to rely on them?

**Comment by randoum** [comment]
@getaaron if you are still on this, would you mind to check #59 and see if your issues are fixed ?

**Comment by getaaron** [comment]
@randoum I have a new job so I don't have access to that project any more. What do you think about adding my example test above to the specs in your PR? Just change `to` to `not_to`

**Comment by randoum** [comment]
@getaaron I'm closing this issue because you are not affected anymore. Thanks
