### ISSUE TITLE
Unexpected result with :text

### ISSUE THREAD

**Issue by PhilippePerret** [kucaahbe/rspec-html-matchers#51]
```
1) Form contains span with question
 Failure/Error: with_tag('span', text: dquestion[:question])

   "Par quel terme désigne-t-on le personnage le plus important du récit ?" expected within "span" in following template:
   <li id="li-q-1" data-qid="1">
   <div class="btns fright tiny">
   <a class="tiny" onclick="QuizQuestion.edit(this)" data-qid="1" data-quiz="quiz_biblio" href="javascript:void(0)">edit</a><a class="tiny" onclick="$('li#li-q-1').remove();QuizQuestion.reordonne_questions()" href="javascript:void(0)">sup</a>
   </div>
   <span>Par quel terme désigne-t-on le personnage le plus important du récit ?</span>
   </li>
```

For info, `dquestion[:question]` contains “Par quel terme désigne-t-on le personnage le plus important du récit ?”, a french question.

Question is indeed in a span tag, a exception raised though…

**Comment by randoum** [comment]
@PhilippePerret do you still have this issue ? Please try with 0.9.0 and paste the part of code concerned by the issue

**Comment by PhilippePerret** [comment]
`
describe 'WITHOUT QUESTION MARK AND NON-BREAKING SPACE' do
  let(:t) { "<div><span>récit</span></div>" }
  let(:q) { "récit" }
  it '=> SUCCESS' do
    expect(t).to have_tag('span') do
      with_tag('span', text: q)
    end
  end
end

describe 'WITH QUESTION MARK AND COMMON SPACE' do
  let(:t) { "<div><span>récit ?</span></div>" }
  let(:q) { "récit ?" }
  it '=> SUCCESS' do
    expect(t).to have_tag('span') do
      with_tag('span', text: q)
    end
  end
end


describe 'WITH QUESTION MARK AND NON-BREAKING SPACE' do
  let(:t) { "<div><span>récit ?</span></div>" }
  let(:q) { "récit ?" }
  it '=> FAILURE' do
    expect(t).to have_tag('span') do
      with_tag('span', text: q)
    end
  end
end
`

**Comment by randoum** [comment]
Your tests are all green on my side. 
Are you sure you are using the last version ?

**Comment by PhilippePerret** [comment]
Yes, randoum. Updated this morning (as you told me) -> 0.9.0

Extract of my gem list : 
    ...
    rack-test (0.6.3)
    rake (10.4.2)
    rdoc (4.2.1)
    rspec (3.5.0)
    rspec-core (3.5.2)
    rspec-expectations (3.5.0)
    rspec-html-matchers (0.9.0, 0.8.0)
    rspec-mocks (3.5.0)
    rspec-support (3.5.0)
    rubyzip (1.2.0)
    sass (3.4.22)
    selenium-webdriver (2.53.4)
    ...

**Comment by PhilippePerret** [comment]
When you've copied-pasted my code, are you sure you still have NON-BREAKING spaces ? Sometime, when copying, non-breaking spaces become breaking spaces.

**Comment by randoum** [comment]
Nop, pasting your code to github certainly sanitize the strings. You need to use unicode escape codes, specially for non printable characters (as a good practice, in general).

**Comment by PhilippePerret** [comment]
Noticed! Thanks!

So? Have you be able to try my code with non-breaking space?

**Comment by randoum** [comment]
You need to paste your code with unicode escape code. I cannot guess where are your nbsp
Thanks

**Comment by PhilippePerret** [comment]
As I told you (in first answer), non-breaking space is before question mark, in french ;-) (so we can be sure it works event without a unicode escape code — we don't use unicode escape code for non-breaking space).
(on a Mac, non-breaking space can be done with ALT + SPACE)
Thanks

**Comment by randoum** [comment]
I'm french, I know well about leading space on double punctuation.

nbsp have a value in every char table, if you work with unicode then
pressing ALT+Space will transparently insert the unicode nbsp char in your
string.
There is no magic about pressing ALT-Space with your macintosh.

I'm asking you again: kindly paste your spec code with nsbp as unicode char.

Regards

2017-02-04 10:04 GMT+01:00 Philippe Perret <notifications@github.com>:

**Comment by randoum** [comment]
Sorry we could not work on this. 
I'm closing it, reopen with more info if needed.

Cheers

**Comment by PhilippePerret** [comment]
randoum, je me permets de répondre en français, puisque je ne maitrise pas suffisamment l'anglais pour la finesse de dialogue que requiert ta demande.

Je sais très bien qu'il n'y a aucune magie dans l'utilisation de ALT-Space… Mais dans le code que j'ai copié, c'est un caractère unicode qui est mis (qui apparait comme une espace, puisque c'est une espace), je ne voyais pas comment remplacer un caractère unicode par un caractère unicode…

Désolé si je n'ai pas compris la demande.

**Comment by randoum** [comment]
Please keep it in English for other users.

I still don't have your issue. Try using the `seen` option
