### ISSUE TITLE
Unexpected result with have_tag ... :onclick

### ISSUE THREAD

**Issue by PhilippePerret** [kucaahbe/rspec-html-matchers#52]
This test fails : 

```
expect(page).to have_tag('a', with: { onclick: "$.proxy(MyClass, 'my_method')()" })
```

Raises a test error.

**Comment by randoum** [comment]
@PhilippePerret So you still have the issue ? Please try with 0.9.0 and paste your code and the error message

**Comment by randoum** [comment]
Feel free to reopen if needed.
