### ISSUE TITLE
Version 0.8.2 yanked?

### ISSUE THREAD

**Issue by shaneog** [kucaahbe/rspec-html-matchers#60]
Was version 0.8.2 yanked? Why?
https://rubygems.org/gems/rspec-html-matchers/versions/0.8.2

This broke a load of deploys for me 😞

**Comment by kucaahbe** [comment]
@shaneog yes, it had this bug #58, please use 0.8.1 or 0.9.0 instead. And probably it worth to put this gem in 'test' group in Gemfile and exclude it from deployment `bundle install` process, so test things do not affect deployments :)

**Comment by shaneog** [comment]
Thanks!
