### ISSUE TITLE
irb: warn: can't alias context from irb_context.

### ISSUE THREAD

**Issue by tbsvttr** [kucaahbe/rspec-html-matchers#69]
After adding this Gem into this environment:

* Ruby 2.5.1
* Rails 5.2.0
* macOS 10.13.4
* ZSH 5.5

It causes after `rails c`:

`irb: warn: can't alias context from irb_context.`

**Comment by kucaahbe** [comment]
looks like answer could be found here: https://github.com/rspec/rspec-rails/issues/1645#issuecomment-229112723
