### ISSUE TITLE
:seen Option Not Matching Seen Text

### ISSUE THREAD

**Issue by sshaw** [kucaahbe/rspec-html-matchers#73]
This does not match:

```rb
expect(<<~HTML).to have_tag("p", :seen => "The following thangz ... 4 days")
<p>
  The following thangz ...
  4
  days
</p>
HTML
```
Looks like `:seen` only ignores leading and trailing space? It should match what's _seen_ by the user: `The following thangz ... 4 days`

**Comment by randoum** [comment]
Please update to 0.9.3
